In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
data = pd.read_csv("train.csv")
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
data = data.drop(['PassengerId','Name','Ticket','Cabin'], axis=1)

In [4]:
le = LabelEncoder()
data['Sex'] = le.fit_transform(data['Sex'])
data['Embarked'] = le.fit_transform(data['Embarked'])

In [5]:
def Nav_Model(col):
    x = data.drop([col], axis=1)
    y = data[col]
    train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.2, random_state = 42)
    model = BernoulliNB()
    model.fit(train_x, train_y)
    ypred = model.predict(test_x)
    print("==================================================================")
    print(f"Accuracy score is {accuracy_score(test_y, ypred)}")
    print("==================================================================")
    print(f"Confusion Matrix: \n{confusion_matrix(test_y, ypred)}")
    print("==================================================================")

## Pclass as Dependent Variable

In [6]:
Nav_Model('Pclass')

Accuracy score is 0.5786516853932584
Confusion Matrix: 
[[15 10 19]
 [ 0  8 34]
 [ 6  6 80]]


## SibSp as Dependent Variable

In [7]:
Nav_Model('SibSp')

Accuracy score is 0.6910112359550562
Confusion Matrix: 
[[108  17   0   0   0   0]
 [ 28  15   0   0   0   0]
 [  3   2   0   0   0   0]
 [  1   1   0   0   0   0]
 [  1   1   0   0   0   0]
 [  0   1   0   0   0   0]]


## Sex as dependent variable

In [8]:
Nav_Model('Sex')

Accuracy score is 0.797752808988764
Confusion Matrix: 
[[53 20]
 [16 89]]


## Parch as Dependent variable

In [9]:
Nav_Model('Parch')

Accuracy score is 0.6966292134831461
Confusion Matrix: 
[[118  15   0   0   0]
 [ 24   6   0   0   0]
 [ 10   2   0   0   0]
 [  1   0   0   0   0]
 [  1   1   0   0   0]]


## Embarked as Dependent variable

In [10]:
Nav_Model('Embarked')

Accuracy score is 0.7303370786516854
Confusion Matrix: 
[[  0   0  36]
 [  0   0  12]
 [  0   0 130]]
