# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np

In [2]:
np.random.randint(0,100,size = (3,3,3))

array([[[42, 62, 87],
        [87, 37, 54],
        [78, 46, 65]],

       [[51,  4, 82],
        [25, 23, 20],
        [15, 74, 90]],

       [[25,  2, 14],
        [46,  1, 71],
        [97, 25, 58]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
arr[1,0] = 1
arr[2,1] = 2
arr[3,2] = 3
arr[4,3] = 4
arr.astype(int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:
arr1 = np.zeros((8,8)).astype(int)
arr1

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
for i in range(0,8,2):
    for j in range(0,8,2):
        arr1[i,j] = 1
        
for i in range(1,8,2):
    for j in range(1,8,2):
        arr1[i,j] = 1
        
print(arr1)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 4. Normalize a 5x5 random matrix

In [7]:
arr_n = np.arange(0,25).reshape(5,5)
norm = np.linalg.norm(arr_n)
normal_arr = arr_n/norm
normal_arr

array([[0.        , 0.01428571, 0.02857143, 0.04285714, 0.05714286],
       [0.07142857, 0.08571429, 0.1       , 0.11428571, 0.12857143],
       [0.14285714, 0.15714286, 0.17142857, 0.18571429, 0.2       ],
       [0.21428571, 0.22857143, 0.24285714, 0.25714286, 0.27142857],
       [0.28571429, 0.3       , 0.31428571, 0.32857143, 0.34285714]])

# 5.  How to find common values between two arrays?

In [8]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,3,1,8,9,0])
np.intersect1d(arr1, arr2)

array([1, 3, 5])

# 6.How to get the dates of yesterday, today and tomorrow?

In [9]:
yest = np.datetime64('today','D') - np.timedelta64(1,'D')
tod = np.datetime64('today','D') 
tom = np.datetime64('today','D') + np.timedelta64(1,'D')
print(f"Yesterday: {yest}\nToday: {tod}\nTomorrow: {tom}")

Yesterday: 2020-07-26
Today: 2020-07-27
Tomorrow: 2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [10]:
A = np.random.randint(0,10, size=(3,3))
B = np.random.randint(0,10, size=(3,3))

np.allclose(A,B)

False

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [11]:
v = np.random.random(10)
v[np.where(v==v.max())] = 0
v

array([0.53773165, 0.        , 0.23530236, 0.26646313, 0.43949234,
       0.62509103, 0.44498887, 0.31967106, 0.16427433, 0.31101794])

# 9. How to print all the values of an array?

In [26]:
arr = np.array([1,2,3,4,5])
for index, ele in enumerate(arr):
    print(f"{ele} is at index {index}")

1 is at index 0
2 is at index 1
3 is at index 2
4 is at index 3
5 is at index 4


# 10.Subtract the mean of each row of a matrix

In [13]:
ar = np.random.randint(3,20, size=(4,5))
ar - ar.mean(axis=1, keepdims=True).astype(int)

array([[ 2,  3, -2, -9,  6],
       [ 4,  4, -3, -6,  1],
       [-3, -2, -2, -2,  9],
       [ 1,  4, -3,  1, -1]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [14]:
arr1 = np.random.randint(10,100,5)
arr1

array([12, 40, 96, 66, 26])

In [15]:
v = [1,0,3,4,2]

arr = arr1[v]+1
arr

array([41, 13, 67, 27, 97])

# 12.How to get the diagonal of a dot product?

In [16]:
arr = np.arange(16).reshape(4,4)
arr1 = np.arange(20,36).reshape(4,4)
a_dot = arr.dot(arr1)
np.diag(a_dot)

array([ 176,  614, 1084, 1586])

# 13.How to find the most frequent value in an array?

In [17]:
from scipy.stats import mode
ar = np.array([1,2,3,4,1,2,1,6,7])
mode(ar)[0]

array([1])

# 14.How to get the n largest values of an array

In [18]:
ar

array([1, 2, 3, 4, 1, 2, 1, 6, 7])

In [19]:
ar.max()

7

# 15.How to create a record array from a regular array?

In [21]:
arr1 = np.array([(1,2,3), (4,5,6), (7,8,9)])
arr2 = np.core.records.fromarrays(arr1.T, names='a, b, c', formats= 'i8,i8,i8')

In [22]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
print(arr2)

[(1, 2, 3) (4, 5, 6) (7, 8, 9)]
